In [28]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [29]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [30]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
np.zeros(4)

array([0., 0., 0., 0.])

In [32]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
noise = np.random.normal(loc = 0, scale = .1, size = 8)
np.round(noise, 3)

array([-0.155,  0.138, -0.017,  0.032, -0.11 ,  0.19 , -0.069,  0.015])

In [34]:
signal = np.array([0.5, 1.2, 1.8, 0.9, 2.1, 1.5, 0.7, 1.1])

signal

array([0.5, 1.2, 1.8, 0.9, 2.1, 1.5, 0.7, 1.1])

In [35]:
signal.shape, signal.ndim, len(signal)

((8,), 1, 8)

In [36]:
signal[0], signal[-1]

(np.float64(0.5), np.float64(1.1))

In [37]:
signal[2:5]

array([1.8, 0.9, 2.1])

In [38]:
signal[::2]

array([0.5, 1.8, 2.1, 0.7])

In [39]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
matrix.shape

(3, 3)

In [41]:
matrix[1, 2]

np.int64(6)

In [42]:
matrix[0, :]

array([1, 2, 3])

In [43]:
matrix[:, 1]

array([2, 5, 8])

In [44]:
a_int = np.array([1, 2, 3])

a_int.dtype

dtype('int64')

In [45]:
a_float = np.array([1., 2., 3.])

a_float.dtype

dtype('float64')

In [46]:
a32 = np.zeros(4, dtype=np.float32)
print(f"dtype: {a32.dtype}   paměť na prvek: {a32.itemsize} B")

dtype: float32   paměť na prvek: 4 B


In [47]:
a_int.astype(float)

array([1., 2., 3.])

In [48]:
flat = np.arange(12)

flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
flat.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
flat.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [51]:
flat.reshape(1, -1).shape, flat.reshape(-1, 1).shape

((1, 12), (12, 1))

In [52]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])

data[[0, 2, 5]]

array([10, 30, 60])

In [53]:
data[[5, 0, 5, 2]]

array([60, 10, 60, 30])

In [54]:
mereni = np.array([[120, 80, 72],
                   [135, 88, 90],
                   [118, 76, 65],
                   [145, 95, 88]])

mereni[[0, 2]]

array([[120,  80,  72],
       [118,  76,  65]])

In [55]:
mask = np.array([True, False, True, False, True, False, True, False])

data[mask]

array([10, 30, 50, 70])

In [56]:
data > 40

array([False, False, False, False,  True,  True,  True,  True])

In [57]:
data[data > 40]

array([50, 60, 70, 80])

In [58]:
data[(data > 20) & (data < 70)]

array([30, 40, 50, 60])

In [59]:
a = np.array([1.0, 2.0, 3.0, 4.0])
b = np.array([0.5, 0.5, 0.5, 0.5])

a + b

array([1.5, 2.5, 3.5, 4.5])

In [60]:
a ** 2

array([ 1.,  4.,  9., 16.])

In [61]:
np.round(np.sqrt(a), 3)

array([1.   , 1.414, 1.732, 2.   ])

In [62]:
print(f"sum: {a.sum()}   mean: {a.mean()}   std: {a.std():.3f}")
print(f"min: {a.min()}   max: {a.max()}")

sum: 10.0   mean: 2.5   std: 1.118
min: 1.0   max: 4.0


In [63]:
a[a > 2].mean()

np.float64(3.5)

In [64]:
mereni = np.array([[120, 80, 72],
                   [135, 88, 90],
                   [118, 76, 65],
                   [145, 95, 88]])

print("Průměr přes všechna data:        ", mereni.mean())
print("Průměr po sloupcích (axis=0):    ", mereni.mean(axis=0))
print("Průměr po řádcích (axis=1):      ", mereni.mean(axis=1))


Průměr přes všechna data:         97.66666666666667
Průměr po sloupcích (axis=0):     [129.5   84.75  78.75]
Průměr po řádcích (axis=1):       [ 90.66666667 104.33333333  86.33333333 109.33333333]


In [65]:
tf = np.array([72, 90, 65, 88])

idx_max = tf.argmax()
idx_min = tf.argmin()

print(f"Nejvyšší TF má pacient {idx_max} (hodnota {tf[idx_max]})")
print(f"Nejnižší TF má pacient {idx_min} (hodnota {tf[idx_min]})")

Nejvyšší TF má pacient 1 (hodnota 90)
Nejnižší TF má pacient 2 (hodnota 65)


In [66]:
print("Index maxima v každém sloupci:", mereni.argmax(axis=0))
print("Index maxima v každém řádku: ", mereni.argmax(axis=1))

Index maxima v každém sloupci: [3 3 1]
Index maxima v každém řádku:  [0 0 0 0]


# ÚKOL: Analýza dat klinické studie

In [71]:
data = np.load("data/pacienti.npy")

data.shape, data[:5]

((20, 3),
 array([[129.6,  78.2,  93. ],
        [109.4,  73.2,  72. ],
        [136.3,  92.2,  61. ],
        [139.1,  78.5,  89. ],
        [ 95.7,  75.7,  80. ]]))

In [74]:
np.mean(data, axis = 1), np.std(data, axis = 1)

(array([100.26666667,  84.86666667,  96.5       , 102.2       ,
         83.8       ,  88.33333333,  90.06666667,  90.33333333,
         98.26666667,  95.16666667, 103.86666667,  99.86666667,
         96.63333333,  94.6       , 103.06666667,  89.8       ,
         91.13333333,  88.06666667,  97.        ,  90.26666667]),
 array([21.60390911, 17.35460234, 30.89109904, 26.44201203,  8.59573538,
        12.42533255, 28.32952916, 22.25942996, 18.70727725, 12.19626537,
        27.08226152, 26.43638066, 21.54844671, 33.4551441 , 20.55258837,
        18.85011052, 28.49331306, 16.48945791, 29.37391133, 26.38513891]))

In [89]:
mask = data[:, 0] >= 140

high_systolic_patients = data[mask]

len(high_systolic_patients), np.mean(high_systolic_patients, axis = 0)[0]

(1, np.float64(141.9))

In [90]:
pulse_pressure = data[:, 0] - data[:, 1]

np.column_stack((data, pulse_pressure))

array([[129.6,  78.2,  93. ,  51.4],
       [109.4,  73.2,  72. ,  36.2],
       [136.3,  92.2,  61. ,  44.1],
       [139.1,  78.5,  89. ,  60.6],
       [ 95.7,  75.7,  80. ,  20. ],
       [105.5,  76.5,  83. ,  29. ],
       [126.9,  85.3,  58. ,  41.6],
       [120.3,  83.7,  67. ,  36.6],
       [124.7,  84.1,  86. ,  40.6],
       [112.2,  84.3,  89. ,  27.9],
       [138.2, 101.4,  72. ,  36.8],
       [136.7,  75.9,  87. ,  60.8],
       [126. ,  74.9,  89. ,  51.1],
       [141.9,  71.9,  70. ,  70. ],
       [132. ,  86.2,  91. ,  45.8],
       [112.1,  91.3,  66. ,  20.8],
       [130.5,  78.9,  64. ,  51.6],
       [110.6,  71.6,  82. ,  39. ],
       [138.2,  71.8,  81. ,  66.4],
       [124.3,  86.5,  60. ,  37.8]])

In [96]:
max_hr_idx = np.argmax(data[:, 2])

max_hr_idx, data[max_hr_idx]

(np.int64(0), array([129.6,  78.2,  93. ]))