In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
noise = np.random.normal(loc = 0, scale = .1, size = 8)
np.round(noise, 3)

array([-0.057, -0.128,  0.042, -0.019, -0.106, -0.023, -0.127, -0.161])